services:
  telegram-bot:
    container_name: telegram-bot
    build: bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DEV=${DEV}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - IMG_BUCKET_NAME=${IMG_BUCKET_NAME}
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - minio

  db_manager:
    container_name: db_manager
    build: db_manager
    environment:
      - DEV=${DEV}
      - POSTGRES_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${POSTGRES_PORT}/images
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq

  minio:
    image: "minio/minio:RELEASE.2025-09-07T16-13-09Z"
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "127.0.0.1:${MINIO_CONSOLE_PORT}:9001"
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        minio server --address "0.0.0.0:9000" --console-address "0.0.0.0:9001" /data
    volumes:
      - .minio:/data
    depends_on:
      - alloy
    healthcheck:
      start_period: 3m
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 20s
      retries: 3
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:4.2"
    container_name: rabbitmq
    ports:
      - "127.0.0.1:${RABBITMQ_CONSOLE_PORT}:8080"
    depends_on:
      - alloy
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  postgres:
    image: "postgres:18"
    container_name: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - .postgres:/var/lib/postgresql/18/docker
    depends_on:
      - alloy
    healthcheck:
      start_period: 3m
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3m
      timeout: 30s
      retries: 1

  uploader:
    container_name: uploader
    build: uploader
    environment:
      - DEV=${DEV}
      - WEAVIATE_PORT=${WEAVIATE_PORT}
      - WEAVIATE_GRPC_PORT=${WEAVIATE_GRPC_PORT}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - EMBEDDER_PORT=${EMBEDDER_PORT}
    restart: unless-stopped
    depends_on:
      - weaviate
      - minio
      - rabbitmq
      - embedder
      - alloy

  embedder:
    container_name: embedder
    build: embedder
    environment:
      - DEV=${DEV}
      - EMBEDDER_PORT=${EMBEDDER_PORT}
    restart: unless-stopped
    depends_on:
      - alloy
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  weaviate:
    image: "semitechnologies/weaviate:1.35.3"
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '${WEAVIATE_PORT}'
      - --scheme
      - http
    volumes:
      - .weaviate:/var/lib/weaviate
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - CLUSTER_HOSTNAME=node1
    restart: unless-stopped
    depends_on:
      - alloy

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./config/alloy.yaml:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    restart: unless-stopped
    ports:
      - "127.0.0.1:${ALLOY_PORT}:12345"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:12345/ready"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 20s
      retries: 3
      start_period: 1m

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    container_name: grafana
    volumes:
      - ./config/grafana.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "127.0.0.1:${GRAFANA_PORT}:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 20s
      retries: 3
      start_period: 1m
    depends_on:
      - loki
      - alloy

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
      - alloy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: 20s
      retries: 3
      start_period: 1m

  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-remote-write-receiver
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "127.0.0.1:${PROMETHEUS_PORT}:9090"

volumes:
  .postgres:
  .minio:
  .weaviate:
# sentry kibana loki grafana prometheus clickhouse elasticsearch redash